version: "3"

services:
  postgres:
    image: postgres:11
    ports:
      - "9001:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  mysql:
    image: mysql:8
    ports:
      - "9002:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
